name: sqflite_common_ffi_async
description: Sqlite API on top on sqlite_async
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

dependencies:
  path: '>=1.8.0 <3.0.0'
  sqflite_common: '>=2.5.0+2 <4.0.0'
  sqflite_common_ffi: '>=2.3.1 <4.0.0'
  sqlite_async: '>=0.5.2 <2.0.0'

dev_dependencies:
  lints: '>=2.0.0'
  test: '>=1.21.0'
