name: sqflite_common_ffi_async
homepage: https://github.com/tekartik/sqflite/tree/master/packages/sqflite_common_ffi_async
description: Sqlite API on top on sqlite_async
version: 0.1.1

environment:
  sdk: ^3.2.0

dependencies:
  path: '>=1.8.0 <3.0.0'
  sqflite_common: '>=2.5.1-2 <4.0.0'
  sqflite_common_ffi: '>=2.3.1 <4.0.0'
  sqlite_async: '>=0.5.2 <2.0.0'

dev_dependencies:
  lints: '>=2.0.0'
  test: '>=1.21.0'
